sqlplus $1 <<EOF > ${HOME}/misc/automation/differences/PayerWalletDifference_$2.log
SELECT * FROM
( SELECT 'PAYER_WALLETS' SOURCE, A.* FROM ( SELECT PAYER_ID_N, WALLET_ID_N, BALANCE_N, TRUNC(EXPIRY_DATE_D), MINIMUM_BALANCE_N FROM PAYER_WALLETS
  MINUS SELECT /*+ FULL(TBL2)  */ PAYER_ID_N, WALLET_ID_N, BALANCE_N, EXPIRY_DATE_D, MINIMUM_BALANCE_N FROM PAYER_WALLETS_BAK TBL2) A
  UNION ALL SELECT 'PAYER_WALLETS_BAK', B.* FROM ( SELECT /*+ FULL(TBL2)  */ PAYER_ID_N, WALLET_ID_N, BALANCE_N, EXPIRY_DATE_D, MINIMUM_BALANCE_N  FROM PAYER_WALLETS_BAK TBL2
  MINUS SELECT PAYER_ID_N, WALLET_ID_N, BALANCE_N, TRUNC(EXPIRY_DATE_D), MINIMUM_BALANCE_N FROM PAYER_WALLETS) B
) ORDER BY  2,1;
EOF



sqlplus $1 <<EOF > ${HOME}/misc/automation/differences/PayerSpendCtrlDifference_$2.log
Select * from(select 'WALLET_SPEND_LIMITS' Source, a.* from (
select /*+ FULL(Tbl1)  */PAYER_ID_N, WALLET_ID_N, SPEND_GROUP_ID_N, MINIMUM_BALANCE_N, BALANCE_N
from   WALLET_SPEND_LIMITS Tbl1
minus select /*+ FULL(Tbl2)  */  PAYER_ID_N, WALLET_ID_N, SPEND_GROUP_ID_N, MINIMUM_BALANCE_N, BALANCE_N
from   WALLET_SPEND_LIMITS_INDB Tbl2  ) A
union all
select 'WALLET_SPEND_LIMITS_INDB', b.* from( select /*+ FULL(Tbl2)  */
PAYER_ID_N, WALLET_ID_N, SPEND_GROUP_ID_N, MINIMUM_BALANCE_N, BALANCE_N from   WALLET_SPEND_LIMITS_INDB Tbl2
minus select /*+ FULL(Tbl1)  */ PAYER_ID_N, WALLET_ID_N, SPEND_GROUP_ID_N, MINIMUM_BALANCE_N, BALANCE_N
from   WALLET_SPEND_LIMITS Tbl1 ) B )
Order by  2,3;
EOF
